steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: "decrypt env"
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --project=$PROJECT_ID
      - --keyring=deploy
      - --key=env
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/api:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/api:latest',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/api:$SHORT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/api:latest'