version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace:cached
      
    command: sleep infinity
    ports: 
      - 6011:6011
    links: 
      - db
    
  db:
    image: postgres
    restart: unless-stopped
    ports: 
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword
