name: Build, push to GitHub, and deploy
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build
      run: |        
        docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/api:${GITHUB_SHA::8} -t docker.pkg.github.com/$GITHUB_REPOSITORY/api:latest -f ci/Dockerfile .
    - name: Publish
      run: |
        docker push docker.pkg.github.com/$GITHUB_REPOSITORY/api:latest && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/api:${GITHUB_SHA::8}